# Generated by Django 5.2.10 on 2026-01-08 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('pages_read', models.IntegerField(default=0, verbose_name='تعداد صفحات کتاب')),
                ('sleep_hours', models.FloatField(default=0, verbose_name='ساعت خواب')),
                ('performance_score', models.IntegerField(default=50, verbose_name='امتیاز عملکرد (0-100)')),
                ('mood', models.CharField(choices=[('awful', 'افتضاح'), ('bad', 'بد'), ('neutral', 'معمولی'), ('good', 'خوب'), ('excellent', 'عالی')], default='neutral', max_length=20)),
                ('song_of_day', models.CharField(blank=True, max_length=100, verbose_name='آهنگ امروز')),
                ('current_book', models.CharField(blank=True, max_length=100, verbose_name='کتاب در حال مطالعه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت روزانه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('personal', 'شخصی'), ('university', 'دانشگاه'), ('work', 'کوئرا'), ('learning', 'یادگیری'), ('learning', 'کار')], max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('category', models.CharField(choices=[('food', 'خوراک'), ('transport', 'حمل و نقل'), ('shopping', 'خرید'), ('other', 'سایر')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('card', models.CharField(choices=[('mellat', 'کارت ملت'), ('melli', 'کارت رفاه'), ('cash', 'نقد')], default='mellat', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
