# Generated by Django 5.2.10 on 2026-03-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_created_at_alter_habitlog_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyLog',
        ),
    ]
