# Generated by Django 5.2.10 on 2026-03-21 11:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_delete_dailylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات کتاب')),
                ('sleep_hours', models.FloatField(default=0.0, verbose_name='ساعت خواب')),
                ('performance_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز عملکرد (۰ تا ۱۰۰)')),
                ('mood', models.CharField(choices=[('excellent', 'عالی 🤩'), ('good', 'خوب 😀'), ('normal', 'معمولی 😐'), ('bad', 'بد 😞'), ('awful', 'خیلی بد 😭')], default='good', max_length=20, verbose_name='حس و حال')),
                ('favorite_song', models.CharField(blank=True, max_length=255, null=True, verbose_name='آهنگ مورد علاقه امروز')),
                ('current_book', models.CharField(blank=True, max_length=255, null=True, verbose_name='کتابی که می\u200cخوانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
