# Generated by Django 5.2.10 on 2026-04-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
