# Generated by Django 5.2.10 on 2026-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_goal_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت زمان (دقیقه)'),
        ),
    ]
