# Generated by Django 5.2.10 on 2026-04-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_task_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت زمان وارد شده تسک (دقیقه)'),
        ),
    ]
