# Generated by Django 5.2.10 on 2026-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_task_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='sport_hours',
            field=models.FloatField(default=0.0, verbose_name='ساعت ورزش'),
        ),
    ]
