# Generated by Django 5.2.10 on 2026-04-07 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_dailylog_sport_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت زمان مشغولی (دقیقه)')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ روز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='tracker.taskcategory', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت زمان',
                'verbose_name_plural': 'ثبت زمان\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
