# Generated by Django 5.2.10 on 2026-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_doingcategory_alter_timelog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doingcategory',
            name='color',
            field=models.CharField(choices=[('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'کله\u200cغازی'), ('cyan', 'فیروزه\u200cای'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('rose', 'رز'), ('gray', 'خاکستری')], default='gray', max_length=20, verbose_name='رنگ'),
        ),
    ]
